### ISSUE TITLE
Non-functional play button in LiaScript modules

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#184]
record number 36

It isn't clear to user whether LiaScript's play button at the bottom of every page is supposed to work/do anything.

**Comment by franzenr** [comment]
should we consider whether we want to set the default style of our modules to textbook, since that's probably the style that makes the most sense for our learners (they would still be able to toggle to presentation or slides if they would like to). 

[Can be set by adding `mode: Textbook`](https://liascript.github.io/course/?https://raw.githubusercontent.com/LiaScript/docs/master/README.md#183) - we could include this in our module template + checks pretty easily
