### ISSUE TITLE
Should we make quiz questions a mandatory part of modules (i.e. every module must have them)? Pros and cons both ways...

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#21]

**Comment by leemc-data-ed** [comment]
Hm, on the one hand I think quiz questions are super useful... but on the other hand, pretty hard to write well! One option we thought about could be that we make quizzes a required part of the modules but if folks aren't comfortable writing them, we (that is, the Arcus data ed. staff) can write quizzes for those people. What does everyone think? Good idea, or too much work on our part?

**Comment by pm0kjp** [comment]
Here's my thinking.  Yes, it can be lots of extra work to add questions if the author hasn't added them, particularly because coming up with reasonable, instructive wrong answers is hard.  At the same time, it would encourage the reviewer to enter a deeper reading of the material as well as a reflection on how well the learning objectives and the content match.  A good middle ground might be "one formative assessment per learning objective" with a strong preference for quiz questions (because they're automated, a well-known idiom, etc.).  If someone doesn't include formative assessments maybe the reviewer suggests just one as a model (so, constructing a single question based on one of the learning objectives) and asks the author to come up with the rest.  Thoughts?

**Comment by pm0kjp** [comment]
We believe that applied knowledge is stickier than unapplied knowledge.  Quiz questions and hands-on activities (that may lead to quiz questions) are a required element of every module.
