### ISSUE TITLE
lack of clarity regarding fill and binwidth commands

### ISSUE THREAD

**Issue by franzenr** [arcus/education_modules#211]
record 117: learner reported not being clear on how to add color using fill or to update the bin width based on module content alone, and they needed to search online for help. 

this is not the first time a learner has reported difficulty with the exercises in this module (see [issue 181](https://github.com/arcus/education_modules/issues/181) ) (this issue is closed, however maybe this is a sign that we didn't add enough clarification)

**Comment by franzenr** [comment]
I did take a quick glance at this module, and there seem to be some inconsistencies w/r/t the level of instructional detail we provide in the markdown content vs what is provided in the .rmd exercise files.

I wonder if perhaps the disconnect is due to us not fully "modularizing" the content well enough -- in the workshop version of this content, maybe we didn't need to be as explicit with us live coding alongside them and explaining in speech in addition to the .rmd content. 

@paytonk I've assigned this to you because you're original author, but feel free to pass along to someone else as bandwidth requires.

**Comment by rosemm** [comment]
I've looked this over, and I feel like there is very clear and explicit instruction for both binwidth and fill in the exercise file instructions (see https://github.com/arcus/education_r_environment/tree/main/r_basics_visualize_data). 
That content isn't in the module text, but the way this (and the other modules in this sequence) is set up is with a fair amount of vital instruction in the rmd files --- I'm hesitant to copy-paste (or move) that instruction into the module because it's so pedagogically important that learners open and use the rmd files. 
Instead, I added a help highlight box after the first histogram (when that bindwitdh error first appears) reminding folks that there's important instructional content in the exercise files and to be sure to follow along there.
