### ISSUE TITLE
Highlight Boxes

### ISSUE THREAD

**Issue by drelliche** [arcus/education_modules#233]
The current highlight boxes are have been used inconsistently and for things outside of their intended purposes.

We need to make sure these div/highlight boxes are used consistently and in a way that makes their purpose clear to learners. Some proposed steps include:

- Updating symbols to be more informative (perhaps replace astronaut?)
- Creating and defining new classes for uses not covered by the current set.
- Adding language to the highlight boxes in addition to the symbol (e.g. Important/Warning/Cool Fact)
![important_div](https://user-images.githubusercontent.com/99294374/200878243-506898f6-a628-49c0-92fa-2909a946fe38.png)

Some brainstorming of new classes and symbols has been recorded in the [highlight_boxes branch](https://github.com/arcus/education_modules/tree/highlight_boxes) in [class_icon_ideas.md](https://github.com/arcus/education_modules/blob/highlight_boxes/class_icon_ideas.md).

**Comment by drelliche** [comment]
Proposed new classes, please add to this list, suggest changes, reject etc.

- **Historical Context** This is a place to give more historical context about how/when/why something came to be the way it currently is. For example: 
    - The reason this command is named `grep` is... 
    - the first `README` file was from 1971,  etc. 
- **Behind the Scenes** This is a place to give a little more technical detail about how something does what it does. For example:
     - The commit number is a hash and associated details
     - In R the `<-` and `=` can both be used for assignment because...
- **Connection** This could be a place to link between modules or topics in ways that might not otherwise be obvious. For example 
     - "If you want to do this in Python instead of in R, check out this module over here" 
- **Cool Fact** This is any cool fact that really doesn't fit into any of our other categories

**Comment by rosemm** [comment]
This sounds awesome! Thanks! Still catching up on the background discussion: Are we talking about just adding new classes, or reworking the whole set? It might be worth reworking, since those classes were just added ad hoc at the beginning, and we have a lot more perspective now to figure out what a useful and consistent set of highlight boxes would be. 
I really like the addition of text --- I think that will go a long way towards keeping us consistent in how we use the different boxes.

**Comment by drelliche** [comment]
@rosemm Reworking any or all of them is certainly on the table, particularly their symbols but also their function and names!

**Comment by rosemm** [comment]
Cool. For context, here's the current list:

```
The style "important" is for important points and key ideas. For example:

<div class = "important">
Tip: It's generally much easier to make any necessary changes to the dataframe, such as mutating variables, before sending it to the plotting command.
</div>

The style "care" is for content related to compassion, self-care, and motivation. For example:

<div class = "care">
This is a topic with a tremendous amount of jargon, which can make resources you may find online hard to understand for folks new to the field. When that happens it's easy to feel like there's something wrong with you if you don't get it, but that's not the case! Those kinds of gatekeeping explanations are a failure on the part of the writer, not the learner.
</div>


The style "help" is for educational first aid --- "help I'm lost!" suggestions. For example:

<div class = "help">
Feeling overwhelmed? It takes a long time to learn git, so don't be disheartened if it doesn't click initially. Just focus on stage, commit, and push. Ignore the rest for now, until you've had a chance to practice just the stage-commit-push process several times.
</div>

The style "warning" alerts users to potential pitfalls. For example:

<div class = "warning">
A common mistake when using `filter` is to write = when you mean ==. Remember that = is for argument assignment, and == is for testing equality in conditions. If you get them mixed up, your code won't run!
</div>

The style "learnmore" alerts users resources for further learning, especially links to a more in-depth discussion of an issue that might be touched on only briefly in the module.

<div class = "learnmore">
To learn more about the theory behind ggplot2, read [Hadley Wickham's article, "A Layered Grammar of Graphics"](http://vita.had.co.nz/papers/layered-grammar.pdf)
</div>

The style "options" is for an aside to let learners know there's another possible approach. For example:

<div class = "options">
You could also skip setting up an OSF account completely and just use github to publish and share your research products, but many people prefer to have OSF links available.
</div>
or
<div class = "options">
To do this in R instead of python, see this other module.
</div>
```

You're all much fresher on this content than I am, of course, but a couple initial ideas I have about reworking existing classes:

- `help` vs `care` is confusing, probably because of the example text I put in for `help`. I would recommend keeping `care` as psycho/emotional support, and making `help` much more concrete troubleshooting guidance. So "You may be feeling super overwhelmed with this content" would be a `care` box, and "If you're getting an error when you try to run this, double check the whitespace in your code --- that's a common mistake here" would be `help`. For the text for each, I might do something like "A little encouragement..." for `care` and "Troubleshooting tip` for `help`. 
- there's also grey area between `warning` and `help`, especially if we restrict `help` to concrete troubleshooting (e.g. "Here's a common mistake you might make" could easily be considered `warning` or `help`). In the name of parsimony, I think we could safely drop either `warning` or `help`, especially with the availability of `important` for anything we want to be super sure to draw attention to (e.g. super critical warnings, like "don't do X or you'll overwrite all your work and won't be able to restore it"). 
- I anticipate some grey area between `connection` and `learnmore`, and possibly also `options`. One way to distinguish would be for `learnmore` to be used just to link to outside additional content, and `connection` for links to our own modules. Text for each might be "We have a module for that!" for `connection` (please feel very free to veto that as too dorky, even among dorks) and "Learn more" for `learnmore`. And we could restrict `options` to non-link things (e.g. "You can also skip setting up an account for this part if you prefer and you'll see be able to do the exercise, but note that you'll be unable to save your work"). Text for `options` might be "Another option..."

**Comment by rosemm** [comment]
Re `history`, in addition to the two examples Elizabeth provided, another good example would be the main vs master discussion in git. Even something like "Wondering why `ggplot2` isn't just called `ggplot`? It's because..." (sidebar: anyone know where that 2 comes from? I don't, and now I'm curious!)

For `connection`, I think we might be able to either drop that class or drop `learnmore`, as they seem very similar to me (unless we do something like reserve `connection` specifically for linking to our own modules, as I mentioned above).

**Comment by rosemm** [comment]
I like your icon suggestions, @franzenr! And I also agree re adding more examples in the docs. I'm happy to consolidate this and do a PR, if it seems like we're at the right moment for that now.

**Comment by rosemm** [comment]
Also, I have a memory of some css @paytonk suggested, to add the text along with the icons. I didn't look at it closely at the time, but I remember someone mentioning it as a solution to avoid weird problems with overlaying text --- is that code available somewhere? Wanting to not reinvent any wheels. 🙂

**Comment by rosemm** [comment]
Proposed final (?) list of classes, with suggested opening text  and icon just after them:

- `answer` "Solution"  ([circle check](https://fontawesome.com/icons/circle-check?s=solid&f=classic)) (this one only gets used during quizzes, but it is technically a highlight box)
- `behind-the-scenes` "Behind the scenes" ([gears](https://fontawesome.com/icons/gears?s=solid&f=classic))
- `care` "A little encouragement" ([hand holding heart](https://fontawesome.com/icons/hand-holding-heart?s=solid&f=classic))
- `cool-fact` "Did you know?" ([face thinking](https://fontawesome.com/icons/face-thinking?s=solid&f=classic))
- `help` "Troubleshooting help" ([circle question](https://fontawesome.com/icons/circle-question?s=regular&f=classic))
- `history` "Historical context" ([globe](https://fontawesome.com/icons/globe?s=solid&f=classic))
- `important` "Important note" ([star](https://fontawesome.com/icons/star?s=solid&f=classic))
- `learnmore` "Learning connection" ([book open cover](https://fontawesome.com/icons/book-open-cover?s=solid&f=classic))
- `options` "Another option" ([scales](https://fontawesome.com/icons/scale-balanced?s=solid&f=classic))
- `warning` "Warning!" ([! triangle](https://fontawesome.com/icons/triangle-exclamation?s=solid&f=classic))

Notes: 

- I'm proposing collapsing `learnmore` and `connection` (and sticking with the `learnmore` label, so it's backwards compatible with our existing modules). This box would be for linking to additional resources/lessons, ours or other people's, for learners wanting to go deeper. 
- there's another class, `hint`, that has been sitting in our css file, but has never been used! Since liascript has hint buttons, I think we shouldn't also have hint boxes, so we should probably just drop that officially.
- please tell me you have a better idea for the `cool-fact` icon...

**Comment by drelliche** [comment]
I have some preference for signs-post over the scales because they feel more like there are two options, possibly both good, as opposed to the scales which feel like we are weighing options and finding one lacking.

I like all of the other symbols and text except for the the `cool fact` thinking face which could maybe be [book-sparkles](https://fontawesome.com/icons/book-sparkles?s=regular&f=classic)?

Lastly, so we preserve this 'how to` for the CSS, here is @pm0kjp 's css for the words:
![image](https://user-images.githubusercontent.com/99294374/202570558-55cc70ec-f3ee-43e2-800f-f89c12af4c26.png)

**Comment by rosemm** [comment]
Oh thank you! Book sparkles is MUCH better! 
Re `options`, I think I vote with Rose that scales is more transparent of a symbol, so maybe let's leave it as that for now and bring it up to the rest of the group at our next meeting for a quick vote?

**Comment by drelliche** [comment]
Could I propose [left-right](https://fontawesome.com/icons/left-right?s=solid&f=classic) maybe as another option for `options`? I associate the scales so heavily with justice/law/courts rather than choice, but if the rest of the group sees them as `options` I'm happy to roll with that.

**Comment by rosemm** [comment]
Left-right works for me, I think! And two votes from Elizabeth ties one vote from each of the Roses ;)

**Comment by franzenr** [comment]
(removing the QA label bc we're only using that for actual Quality Assurances, not for changing elements of the quality we try to assure)

**Comment by franzenr** [comment]
so unfortunately, taking a look at those icons again, I'm realizing that some are Pro icons. We may have money to finagle paying for icons (paging @pm0kjp !) but perhaps not, so we should think of alternatives if we need to stick to the free icons. I think it might be subscription based, not individual purchase based, in which case I think it might not make sense to use the Pro icons even if we were to have $$ right now. 

`learn-more`: sadly, [book-open-cover](https://fontawesome.com/icons/book-open-cover?s=regular&f=classic)  is pro, however [book-open](https://fontawesome.com/icons/book-open?s=regular&f=classic) is not, so that seems like an easy enough swap! Alternatively, we could do [book](https://fontawesome.com/icons/book?s=solid&f=classic). 

`cool-fact`: both [book-sparkles](https://fontawesome.com/icons/book-sparkles?s=solid&f=classic) and [face-thinking](https://fontawesome.com/icons/face-thinking?s=solid&f=classic) are Pro, so back to the drawing board for this one. I don't have any replacement suggestions off the top of my head at the moment. 

This isn't a Pro issue, but I'm not sure I love the globe for history -- personally I kinda like the [compass-drafting](https://fontawesome.com/icons/compass-drafting?s=solid&f=classic) suggestion better, although I don't necessarily think either of them invokes history particularly well. 
maybe also [landmark](https://fontawesome.com/icons/landmark?s=solid&f=classic) or [clock-rotate-left](https://fontawesome.com/icons/clock-rotate-left?s=solid&f=classic) 
(We definitely shouldn't use this one both because it's Pro and also a cultural reference, but I just want to acknowledge my love for the [flux-capacitor](https://fontawesome.com/icons/flux-capacitor?s=light&f=classic) icon.

**Comment by rosemm** [comment]
Ah, good catch! Thanks, @franzenr. 
For `cool-fact`, I'm truly tempted by [wand-sparkles](https://fontawesome.com/icons/wand-sparkles?s=solid&f=classic) but it really isn't related, it's just charming. A more serious suggestion is [magnifying-glass](https://fontawesome.com/icons/magnifying-glass?s=solid&f=classic). 
For `history`, I like clock-rotate-left! Good find!

On another note, I'm realizing we should standardize how we do multiword classes (learnmore, cool-fact, behind-the-scenes). Although my strong preference is for snake or kabob, since it's so much easier to read, *someone* (me) put `learnmore` in as all one word originally, and changing it now would require going back and updating past modules. And we have plenty to work on right now already without creating more little tasks. So perhaps `coolfact` and `behindthescences`?

**Comment by rosemm** [comment]
So I just remembered a magnifying glass is the universal symbol for "search", so maybe a bad choice for `coolfact`? It might be fine. But another suggestion is [person-chalkboard](https://fontawesome.com/icons/person-chalkboard?s=solid&f=classic) (like someone saying "did you know this cool fact?"), or maybe using the star currently employed for `important`, and making something like [key](https://fontawesome.com/icons/key?s=solid&f=classic) the icon for `important` instead.

**Comment by drelliche** [comment]
Maybe [brain](https://fontawesome.com/icons/brain?s=solid&f=classic) or [microscope](https://fontawesome.com/icons/microscope?s=solid&f=classic) for `coolfact`?

**Comment by rosemm** [comment]
Ooo brain! I love it!

**Comment by rosemm** [comment]
So I have an updated version of the css file available: [https://github.com/arcus/education_modules/tree/highlight_box_update](https://github.com/arcus/education_modules/tree/highlight_box_update) But I realized I don't know how to test it without actually putting it into production (i.e. saving over our current css file in aws). I feel like I should know how to do this, but I don't! Any ideas?

**Comment by pm0kjp** [comment]
I do have some ideas! 

* Load a new css script with a different name to AWS (..._version2.css), change the yaml link to that css on your markdown in a new branch that switches a couple of modules to the newer version.   If it works well, then remove the new file, overwrite the old file, delete your test branch
* Use "inspector" mode to update the css in the webpage to what you intend to change it to (if this is cryptic I can explain in a quick call)

**Comment by rosemm** [comment]
Ooo changing it in inspector! What a clever idea! I’ll give that a try. Thanks!

**Comment by franzenr** [comment]
re standardization of multi-word classes -- it would be pretty trivial for me to write a line or two in bash that updates all instances of `learnmore` to `learn-more`, so I wouldn't weigh the effort of changing it too heavily in the kebab vs smooshedtogethermisery consideration

**Comment by drelliche** [comment]
This is a list of all modules that need to be updated to the new template: 
- [ ] bash_103_combining_commands
- [ ] bash_command_line_101
- [ ] bash_command_line_102
- [ ] bash_conditionals_loops
- [ ] data_storage_models
- [ ] data_visualization_in_ggplot2
- [ ] data_visualization_in_open_source_software
- [ ] data_visualization_in_seaborn
- [ ] demystifying_geospatial_data
- [ ] demystifying_python
- [ ] demystifying_sql
- [ ] directories_and_file_paths
- [ ] git_creation_and_tracking
- [ ] git_history_of_project
- [ ] git_intro
- [ ] git_setup_mac_and_linux
- [ ] git_setup_windows
- [ ] how_to_troubleshoot
- [ ] learning_to_learn
- [ ] omics_orientation
- [ ] pandas_transformation
- [ ] python_basics_writing_python_code
- [ ] r_basics_introduction
- [ ] r_basics_transform_data
- [ ] r_basics_visualizae_data
- [ ] r_missing_values
- [ ] r_reshape_long_wide
- [ ] reproducibility
- [ ] sql_basic
- [ ] sql_intermediate
- [ ] statistical_tests
- [ ] tidy_data
- [ ] using_redcap_api

**Comment by drelliche** [comment]
This issue has been closed by https://github.com/arcus/education_modules/pull/241 

A new issue (https://github.com/arcus/education_modules/issues/242) has been created to bring all of the modules up to the new standards.
