### ISSUE TITLE
error messages to visualize code

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#348]
When user tried to add print command to visualize the code when replacing male with "m", user kept getting error messages. See record 370 in REDCap

**Comment by rosemm** [comment]
I think the learner was on this page? https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/pandas_transform/pandas_transform.md#19

**Comment by drelliche** [comment]
I can't replicate the error messages, but I suspect that this is because they mistyped something and this is a lot to type all at once, especially without the ability to use left/right arrows to move around.

As a stopgap until we get pyodide implemented, I'll add in a commented out print command so that people don't have to type it at all, just un-comment it.
