### ISSUE TITLE
Explain code construction

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#353]
Some areas could grow from more precise explanations. For example in the hands-on R section, "rename_with(~str_remove(., '_2'))" as well as the final part with "across" would benefit from more step-by-step instructions relating to how the code was written / decided on.

See record 334 in REDCap.

**Comment by rosemm** [comment]
I looked through the module (in this repo) and hands-on coding files (in education_r_environment), and I see that there's actually a lot of thorough explanation for that `rename_with` and `mutate` code already (I took out the across since it wasn't needed). 
I think maybe the core of the learner's confusion is around the last piece they mention, "instructions relating to how the code was written / decided on". I addressed this (hopefully!) by [adding a care box](https://github.com/arcus/education_modules/pull/434/commits/c2d0d72b76fd6e280e3cf55ebacfe6bce28999f5) after that section emphasizing that they shouldn't feel like they would come up with the same code we come up with, and that any code that works is good code.
