### ISSUE TITLE
lead up to na.action quiz question

### ISSUE THREAD

**Issue by pm0kjp** [arcus/education_modules#617]
record number: 1057

Description of issue: User reports that na.action was never mentioned but then addressed in a quiz question.  Consider adding or changing material around na.action.

**Comment by rosemm** [comment]
This is a situation where the content is in the exercise file rather than in the module text itself. If a learner goes through the module without looking at the accompanying exercises file, then indeed `na.action` shows up in the quiz with no prior explanation. But we intentionally use the exercise files for quite a lot of crucial instruction (not just in this module, but in most of them); I'm reluctant to move that explanation to the module file because it's so important that learners open and work through the exercises to learn this content.
I considered adding more clear signposting to the module to push learners to open and use the exercise file, but it's already in there, including in the specific section mentioned in the comment here. The module content gives an overview of what will be taught ("The example code will walk you through several R functions with different kinds of options for handling missingness.") and then instructs the learner to go back to the exercise file including which specific line numbers to look at. I doubt putting in another reminder would help.
